services:
  - type: web
    name: final-kcb-telur
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nama_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quial_app.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: final-kcb-telur.onrender.com
